import Signup from './Register';
import AddClass from './AddClass';
import TeacherClassList from './TeacherClassList';
import TeacherStudentList from './TeacherStudentList';
import TeacherProjectList from './TeacherProjectList';
import AdminTeacherList from './AdminTeacherList';
import AdminStudentList from './AdminStudentList';
import StudentClassList from './StudentClassList';
import StudentProjectList from './StudentProjectList';
import Enroll from './Enroll';
export { Signup, TeacherClassList, TeacherStudentList, TeacherProjectList, AdminTeacherList, AdminStudentList, StudentClassList, Enroll, StudentProjectList, AddClass  };
